### ISSUE TITLE
Missing setting variables in the vscode settings page

### ISSUE THREAD

**Issue by alexchapar** [slcp/stryker-runner#179]
## Description of the problem
The configured settings do not show up in the vscode settings page. That said, it seems to work if defined in the settings.json

## Expected behaviour
It would be nice to have them showed up in the vscode setting page

## Possible fix
In the package.json, change the “configuration” section to be a child of “contributes” seems to fix the issue (I'll propose a fix soon)

## Versions/OS
- vscode v1.77
- stryker-runner v0.0.40
- windows

**Comment by slcp** [comment]
Thanks for raising this and the PR, having checked the manifest spec the `configuration` block should have always been in that position so I think had I got lucky with it still being picked up.

I'll look at getting that PR merged and a release pushed out.

**Comment by slcp** [comment]
Merged #180 :)

Thanks for the improvements!!
